version: '3.9'

services:
  postgres:
    image: postgres:17.5 # same as version on my lap
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
    ports:
      - "5431:5432"
    volumes:
      - ./data:/data:ro
      - ./sql_scripts:/docker-entrypoint-initdb.d:ro
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command:
      - postgres
      - -c
      - max_connections=1000
      - -c
      - shared_buffers=256MB
      - -c
      - effective_cache_size=768MB
      - -c
      - maintenance_work_mem=64MB
      - -c
      - checkpoint_completion_target=0.7
      - -c
      - wal_buffers=16MB
      - -c
      - default_statistics_target=100
      # --- Advanced Logging Settings (MODIFIED LINES HERE) ---
      - -c
      - "log_destination=stderr" # Changed to double quotes, no internal single quotes
      - -c
      - log_statement=all        # No quotes needed for 'all'
      - -c
      - log_duration=on          # No quotes needed for 'on'
      - -c
      - log_connections=on
      - -c
      - log_disconnections=on
      - -c
      - log_error_verbosity=default
      - -c
      - "log_line_prefix=%m [%p]: %q%u@%d " # Changed to double quotes. The space at the end is part of the prefix.